// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVffInd3wVyI0yeO1A_Dtf1aG1-RfZRos',
    appId: '1:772715593387:web:706491be07156201cf81ee',
    messagingSenderId: '772715593387',
    projectId: 'todo-app-44484',
    authDomain: 'todo-app-44484.firebaseapp.com',
    storageBucket: 'todo-app-44484.firebasestorage.app',
    measurementId: 'G-61JHL5G3HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbM9TkA96G852dV_hF5EFKv5q4lqfuDY',
    appId: '1:772715593387:android:2d8625e3d7ae83d6cf81ee',
    messagingSenderId: '772715593387',
    projectId: 'todo-app-44484',
    storageBucket: 'todo-app-44484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2qUUWnYt19y2DMFfrqvP5U8D0UijF9t0',
    appId: '1:772715593387:ios:209b18db0973410ecf81ee',
    messagingSenderId: '772715593387',
    projectId: 'todo-app-44484',
    storageBucket: 'todo-app-44484.firebasestorage.app',
    iosBundleId: 'com.example.sqfliteLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2qUUWnYt19y2DMFfrqvP5U8D0UijF9t0',
    appId: '1:772715593387:ios:209b18db0973410ecf81ee',
    messagingSenderId: '772715593387',
    projectId: 'todo-app-44484',
    storageBucket: 'todo-app-44484.firebasestorage.app',
    iosBundleId: 'com.example.sqfliteLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVffInd3wVyI0yeO1A_Dtf1aG1-RfZRos',
    appId: '1:772715593387:web:efb2c5631fedb2ffcf81ee',
    messagingSenderId: '772715593387',
    projectId: 'todo-app-44484',
    authDomain: 'todo-app-44484.firebaseapp.com',
    storageBucket: 'todo-app-44484.firebasestorage.app',
    measurementId: 'G-HLZ0S9RET6',
  );
}
